[package]
name        = "orchinus"
version     = "0.1.0"
edition     = "2021"
authors     = ["George Miao <gm@miao.dev>"]
license     = "Apache"
description = "Decentralized MQ implementation with SWIM and CRDT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# hash
blake3-std = "0"

# random number
rand = "0.8"

# networking
quinn = "0.9.3"

# runtime
tokio   = { version = "1", features = ["full"] }
futures = "0.3"

# serializer
serde   = { version = "1.0", features = ["derive"] }
bincode = "1.3"

# debug
tracing = "0.1"

# utils
bitmask            = "0.5"
mod_use            = "0.2"
crossbeam-skiplist = "0.1.1"
thiserror          = "1.0.38"

[dev-dependencies]
# logger
tracing-subscriber = "0.3"
